#-------------------------------
# General Site Settings
title: Karen Xie's Blog
logo: logo.svg # You can add own logo.
description: Learn, grow, pass it on. My learnings on my journey as a developer.


#-------------------------------
# Author Settings
author:
  name: Karen Xie
  image: profile-photo.jpg
  say-hello: Hello, I’m <strong>Karen Xie</strong>.
  bio: This is my blog where I share raw thoughts as I learn my way through my career as a developer.


#-------------------------------
# Contact links
linkedin: https://www.linkedin.com/in/karxie

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: karenxie # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: knittedk # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-188535335-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
